### ISSUE TITLE
Add support for CI config removal 

### ISSUE THREAD

**Issue by matzew** [openshift-knative/hack#48]
When removing CI config like in [here](https://github.com/openshift-knative/hack/commit/9e59c5542ac12bd6cc5e1b78d3917d6914b9a827), the job should:
* reflect the removal on the `openshift/release` fork and also remove them there, for the branch
* reflect the related image mirror file, when a complete version is removed

**Comment by pierDipi** [comment]
@ReToCode @skonto for this to move forward we need to make sure that every supported version is configured in hack since with this issue implemented every CI job configuration for previous versions will be deleted as the hack tool will "reconcile" the directory as opposed to be additive only, can you please give an hack for serving repositories if that's the case?

**Comment by pierDipi** [comment]
Even if that's not the case currently that info might be useful as we know when this is ready to be implemented

**Comment by ReToCode** [comment]
Serving has the full config generated from 1.9, so we should be fine after 1.29 is out of support. As per https://access.redhat.com/product-life-cycles?product=Red%20Hat%20OpenShift%20Serverless, this will be on `October 18, 2023`.

**Comment by pierDipi** [comment]
Completed by https://github.com/openshift-knative/hack/pull/93
